// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: github.com/na4ma4/go-healthcheck/health.proto

package healthcheck

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_UNKNOWN  Status = 0
	Status_STARTING Status = 1
	Status_RUNNING  Status = 2
	Status_FINISHED Status = 3
	Status_ERRORED  Status = 4
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "UNKNOWN",
		1: "STARTING",
		2: "RUNNING",
		3: "FINISHED",
		4: "ERRORED",
	}
	Status_value = map[string]int32{
		"UNKNOWN":  0,
		"STARTING": 1,
		"RUNNING":  2,
		"FINISHED": 3,
		"ERRORED":  4,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_github_com_na4ma4_go_healthcheck_health_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_github_com_na4ma4_go_healthcheck_health_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_github_com_na4ma4_go_healthcheck_health_proto_rawDescGZIP(), []int{0}
}

type ReportStatus int32

const (
	ReportStatus_NOTSET ReportStatus = 0
	ReportStatus_RED    ReportStatus = 1
	ReportStatus_YELLOW ReportStatus = 2
	ReportStatus_GREEN  ReportStatus = 3
)

// Enum value maps for ReportStatus.
var (
	ReportStatus_name = map[int32]string{
		0: "NOTSET",
		1: "RED",
		2: "YELLOW",
		3: "GREEN",
	}
	ReportStatus_value = map[string]int32{
		"NOTSET": 0,
		"RED":    1,
		"YELLOW": 2,
		"GREEN":  3,
	}
)

func (x ReportStatus) Enum() *ReportStatus {
	p := new(ReportStatus)
	*p = x
	return p
}

func (x ReportStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReportStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_github_com_na4ma4_go_healthcheck_health_proto_enumTypes[1].Descriptor()
}

func (ReportStatus) Type() protoreflect.EnumType {
	return &file_github_com_na4ma4_go_healthcheck_health_proto_enumTypes[1]
}

func (x ReportStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReportStatus.Descriptor instead.
func (ReportStatus) EnumDescriptor() ([]byte, []int) {
	return file_github_com_na4ma4_go_healthcheck_health_proto_rawDescGZIP(), []int{1}
}

type CoreProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         map[string]*ItemProto  `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoreProto) Reset() {
	*x = CoreProto{}
	mi := &file_github_com_na4ma4_go_healthcheck_health_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoreProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoreProto) ProtoMessage() {}

func (x *CoreProto) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_na4ma4_go_healthcheck_health_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoreProto.ProtoReflect.Descriptor instead.
func (*CoreProto) Descriptor() ([]byte, []int) {
	return file_github_com_na4ma4_go_healthcheck_health_proto_rawDescGZIP(), []int{0}
}

func (x *CoreProto) GetItems() map[string]*ItemProto {
	if x != nil {
		return x.Items
	}
	return nil
}

type ItemProto struct {
	state         protoimpl.MessageState           `protogen:"open.v1"`
	Name          string                           `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Lifecycle     []*EventProto                    `protobuf:"bytes,2,rep,name=lifecycle,proto3" json:"lifecycle,omitempty"`
	Times         map[int32]*timestamppb.Timestamp `protobuf:"bytes,3,rep,name=times,proto3" json:"times,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Duration      *durationpb.Duration             `protobuf:"bytes,10,opt,name=duration,proto3" json:"duration,omitempty"`
	StartTime     *timestamppb.Timestamp           `protobuf:"bytes,11,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	Status        Status                           `protobuf:"varint,30,opt,name=status,proto3,enum=healthcheck.Status" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemProto) Reset() {
	*x = ItemProto{}
	mi := &file_github_com_na4ma4_go_healthcheck_health_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemProto) ProtoMessage() {}

func (x *ItemProto) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_na4ma4_go_healthcheck_health_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemProto.ProtoReflect.Descriptor instead.
func (*ItemProto) Descriptor() ([]byte, []int) {
	return file_github_com_na4ma4_go_healthcheck_health_proto_rawDescGZIP(), []int{1}
}

func (x *ItemProto) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ItemProto) GetLifecycle() []*EventProto {
	if x != nil {
		return x.Lifecycle
	}
	return nil
}

func (x *ItemProto) GetTimes() map[int32]*timestamppb.Timestamp {
	if x != nil {
		return x.Times
	}
	return nil
}

func (x *ItemProto) GetDuration() *durationpb.Duration {
	if x != nil {
		return x.Duration
	}
	return nil
}

func (x *ItemProto) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *ItemProto) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_UNKNOWN
}

type EventProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Status        Status                 `protobuf:"varint,2,opt,name=status,proto3,enum=healthcheck.Status" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventProto) Reset() {
	*x = EventProto{}
	mi := &file_github_com_na4ma4_go_healthcheck_health_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventProto) ProtoMessage() {}

func (x *EventProto) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_na4ma4_go_healthcheck_health_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventProto.ProtoReflect.Descriptor instead.
func (*EventProto) Descriptor() ([]byte, []int) {
	return file_github_com_na4ma4_go_healthcheck_health_proto_rawDescGZIP(), []int{2}
}

func (x *EventProto) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *EventProto) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_UNKNOWN
}

func (x *EventProto) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var file_github_com_na4ma4_go_healthcheck_health_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.EnumValueOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         33000,
		Name:          "healthcheck.display_name",
		Tag:           "bytes,33000,opt,name=display_name",
		Filename:      "github.com/na4ma4/go-healthcheck/health.proto",
	},
}

// Extension fields to descriptorpb.EnumValueOptions.
var (
	// optional string display_name = 33000;
	E_DisplayName = &file_github_com_na4ma4_go_healthcheck_health_proto_extTypes[0]
)

var File_github_com_na4ma4_go_healthcheck_health_proto protoreflect.FileDescriptor

const file_github_com_na4ma4_go_healthcheck_health_proto_rawDesc = "" +
	"\n" +
	"-github.com/na4ma4/go-healthcheck/health.proto\x12\vhealthcheck\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\x1a google/protobuf/descriptor.proto\"\x96\x01\n" +
	"\tCoreProto\x127\n" +
	"\x05items\x18\x01 \x03(\v2!.healthcheck.CoreProto.ItemsEntryR\x05items\x1aP\n" +
	"\n" +
	"ItemsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.healthcheck.ItemProtoR\x05value:\x028\x01\"\x84\x03\n" +
	"\tItemProto\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x125\n" +
	"\tlifecycle\x18\x02 \x03(\v2\x17.healthcheck.EventProtoR\tlifecycle\x127\n" +
	"\x05times\x18\x03 \x03(\v2!.healthcheck.ItemProto.TimesEntryR\x05times\x125\n" +
	"\bduration\x18\n" +
	" \x01(\v2\x19.google.protobuf.DurationR\bduration\x129\n" +
	"\n" +
	"start_time\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x12+\n" +
	"\x06status\x18\x1e \x01(\x0e2\x13.healthcheck.StatusR\x06status\x1aT\n" +
	"\n" +
	"TimesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x120\n" +
	"\x05value\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x05value:\x028\x01\"\x8d\x01\n" +
	"\n" +
	"EventProto\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12+\n" +
	"\x06status\x18\x02 \x01(\x0e2\x13.healthcheck.StatusR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage*\x8e\x01\n" +
	"\x06Status\x12\x18\n" +
	"\aUNKNOWN\x10\x00\x1a\v\u008e\x10\aunknown\x12\x1a\n" +
	"\bSTARTING\x10\x01\x1a\f\u008e\x10\bstarting\x12\x18\n" +
	"\aRUNNING\x10\x02\x1a\v\u008e\x10\arunning\x12\x1a\n" +
	"\bFINISHED\x10\x03\x1a\f\u008e\x10\bfinished\x12\x18\n" +
	"\aERRORED\x10\x04\x1a\v\u008e\x10\aerrored*:\n" +
	"\fReportStatus\x12\n" +
	"\n" +
	"\x06NOTSET\x10\x00\x12\a\n" +
	"\x03RED\x10\x01\x12\n" +
	"\n" +
	"\x06YELLOW\x10\x02\x12\t\n" +
	"\x05GREEN\x10\x03:F\n" +
	"\fdisplay_name\x12!.google.protobuf.EnumValueOptions\x18\xe8\x81\x02 \x01(\tR\vdisplayNameB.Z,github.com/na4ma4/go-healthcheck;healthcheckb\x06proto3"

var (
	file_github_com_na4ma4_go_healthcheck_health_proto_rawDescOnce sync.Once
	file_github_com_na4ma4_go_healthcheck_health_proto_rawDescData []byte
)

func file_github_com_na4ma4_go_healthcheck_health_proto_rawDescGZIP() []byte {
	file_github_com_na4ma4_go_healthcheck_health_proto_rawDescOnce.Do(func() {
		file_github_com_na4ma4_go_healthcheck_health_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_github_com_na4ma4_go_healthcheck_health_proto_rawDesc), len(file_github_com_na4ma4_go_healthcheck_health_proto_rawDesc)))
	})
	return file_github_com_na4ma4_go_healthcheck_health_proto_rawDescData
}

var file_github_com_na4ma4_go_healthcheck_health_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_github_com_na4ma4_go_healthcheck_health_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_github_com_na4ma4_go_healthcheck_health_proto_goTypes = []any{
	(Status)(0),                           // 0: healthcheck.Status
	(ReportStatus)(0),                     // 1: healthcheck.ReportStatus
	(*CoreProto)(nil),                     // 2: healthcheck.CoreProto
	(*ItemProto)(nil),                     // 3: healthcheck.ItemProto
	(*EventProto)(nil),                    // 4: healthcheck.EventProto
	nil,                                   // 5: healthcheck.CoreProto.ItemsEntry
	nil,                                   // 6: healthcheck.ItemProto.TimesEntry
	(*durationpb.Duration)(nil),           // 7: google.protobuf.Duration
	(*timestamppb.Timestamp)(nil),         // 8: google.protobuf.Timestamp
	(*descriptorpb.EnumValueOptions)(nil), // 9: google.protobuf.EnumValueOptions
}
var file_github_com_na4ma4_go_healthcheck_health_proto_depIdxs = []int32{
	5,  // 0: healthcheck.CoreProto.items:type_name -> healthcheck.CoreProto.ItemsEntry
	4,  // 1: healthcheck.ItemProto.lifecycle:type_name -> healthcheck.EventProto
	6,  // 2: healthcheck.ItemProto.times:type_name -> healthcheck.ItemProto.TimesEntry
	7,  // 3: healthcheck.ItemProto.duration:type_name -> google.protobuf.Duration
	8,  // 4: healthcheck.ItemProto.start_time:type_name -> google.protobuf.Timestamp
	0,  // 5: healthcheck.ItemProto.status:type_name -> healthcheck.Status
	8,  // 6: healthcheck.EventProto.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 7: healthcheck.EventProto.status:type_name -> healthcheck.Status
	3,  // 8: healthcheck.CoreProto.ItemsEntry.value:type_name -> healthcheck.ItemProto
	8,  // 9: healthcheck.ItemProto.TimesEntry.value:type_name -> google.protobuf.Timestamp
	9,  // 10: healthcheck.display_name:extendee -> google.protobuf.EnumValueOptions
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	10, // [10:11] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_github_com_na4ma4_go_healthcheck_health_proto_init() }
func file_github_com_na4ma4_go_healthcheck_health_proto_init() {
	if File_github_com_na4ma4_go_healthcheck_health_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_na4ma4_go_healthcheck_health_proto_rawDesc), len(file_github_com_na4ma4_go_healthcheck_health_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   5,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_github_com_na4ma4_go_healthcheck_health_proto_goTypes,
		DependencyIndexes: file_github_com_na4ma4_go_healthcheck_health_proto_depIdxs,
		EnumInfos:         file_github_com_na4ma4_go_healthcheck_health_proto_enumTypes,
		MessageInfos:      file_github_com_na4ma4_go_healthcheck_health_proto_msgTypes,
		ExtensionInfos:    file_github_com_na4ma4_go_healthcheck_health_proto_extTypes,
	}.Build()
	File_github_com_na4ma4_go_healthcheck_health_proto = out.File
	file_github_com_na4ma4_go_healthcheck_health_proto_goTypes = nil
	file_github_com_na4ma4_go_healthcheck_health_proto_depIdxs = nil
}
